if(typeof LANGS == "undefined") var LANGS = {'ES':{}};
LANGS.ES = {
	"FE_UPLOAD" : "Subir archivos",
	"FE_CREATE_DIRECTORY" : "Crear carpeta",
	"FE_CANCEL" : "Cancelar",
	"FE_DELETE" : "Borrar",
	"FE_CLEAR" : "Limpiar",
	"FE_SEARCH_NAME_FILES" : "Buscar archivos",
	"FE_ADD_FILES" : "Agregar archivos",
	"FE_START_UPLOAD" : "Iniciar subida",
	"FE_CANCEL_UPLOAD" : "Cancelar subida",
	"FE_NEW_FOLDER" : "Nueva carpeta",
	"FE_NAME" : "Nombre",
	"FE_CLOSE" : "Cerrar",
	"FE_SAVE" : "Guardar",
	"FE_RENAME" : "Renombrar",
	"FE_ENTER_NAME" : "Ingresar nombre",
	"FE_MAX_FILES_UPLOAD" : "Máximo número de archivos: ",
	"FE_FILENAME" : "Nombre de archivo: ",
	"FE_LAST_MODIFIED" : "Última modificación: ",
	"FE_SIZE" : "Tamaño: ",
	"FE_DELETE_SELECTED" : "Eliminar seleccionados",
	"FE_INSERT_SELECTED" : "Insertar seleccionados",
	"FE_VIEWS" : "Vistas: ",
	"FE_VIEW_MINIATURE" : "Vista miniatura",
	"FE_VIEW_DETAILS" : "Vista detalle",
	"FE_NOMBRE" : "Nombre",
	"FE_TIPO" : "Tipo",
	"FE_TAMANO" : "Tamaño",
	"FE_DATE" : "Fecha",
	"FE_ACTIONS" : "Acciones",
	"FE_VIEW" : "Ver",
	"FE_DOWNLOAD" : "Descargar",
	"FE_INFORMATION" : "Información",
	"FE_BACK" : "Subir",
	"BE_NEW_FOLDER_CREATED" : "Carpeta creada: ",
	"BE_NEW_FOLDER_EXISTED" : "Carpeta ya existe: ",
	"BE_GETFILEALL_NOT_LEIBLE" : "Archivo no leible",
	"BE_GETFILEALL_NOT_PERMITIDO" : "Archivo no permitido",
	"BE_GETFILEALL_NOT_EXISTED" : "Archivo no existe",
	"BE_UPLOADALL_UPLOADS" : "Subido: ",
	"BE_UPLOADALL_NOT_UPLOADS" : "No permitido: ",
	"BE_UPLOAD_MAX_UPLOAD" : "Máximo archivos permitidos: ",
	"BE_DELETE_DELETED" : "Archivo borrado",
	"BE_DELETE_NOT_EXIED" : "Archivo no existe",
	"BE_RENAME_MODIFIED" : "Archivo modificado",
	"BE_RENAME_EXISTED" : "Archivo ya existe",
	"BE_RENAME_NOT_EXISTS" : "Archivo no existe",
	"BE_RUN_NOT_VALID" : "No valido: ",
	"BE_RENAME_EXT_NOT_EQUALS" : "La extensión no es igual",
	"BE_RENAME_FILENAME_NOT_VALID" : "Nombre de archivo no valido",
	"FE_MOVE" : "Mover",
	"BE_MOVE_MOVED" : "Archivo movido",
	"BE_MOVE_EXISTED" : "Archivo ya existe",
	"BE_MOVE_NOT_EXISTS" : "Archivo no existe",
	"BE_MOVE_FILENAME_NOT_VALID" : "Nombre de archivo no valido",
	"FE_FOLDER" : "Carpeta",
	"BE_MOVE_PATH_NOT_VALID" : "Ruta no valida",
	"BE_MOVE_FOLDER_EXISTED" : "Carpeta ya existe"
};