if(typeof LANGS == "undefined") var LANGS = {'FR':{}};
LANGS.FR = {
	"FE_UPLOAD" : "Fichiers envoyés",
	"FE_CREATE_DIRECTORY" : "Créer répertoire",
	"FE_CANCEL" : "Annuler",
	"FE_DELETE" : "Supprimer",
	"FE_CLEAR" : "Nettoyer",
	"FE_SEARCH_NAME_FILES" : "Rechercher fichiers",
	"FE_ADD_FILES" : "Ajouter fichiers",
	"FE_START_UPLOAD" : "Demarrer l'envoi",
	"FE_CANCEL_UPLOAD" : "Annuler l'envoi",
	"FE_NEW_FOLDER" : "Nouveau répertoire",
	"FE_NAME" : "Nom",
	"FE_CLOSE" : "Fermer",
	"FE_SAVE" : "Enregistrer",
	"FE_RENAME" : "Renommer",
	"FE_ENTER_NAME" : "Entrer nom",
	"FE_MAX_FILES_UPLOAD" : "Nombre maximum de fichiers: ",
	"FE_FILENAME" : "Nom du fichier : ",
	"FE_LAST_MODIFIED" : "Dernier modifié : ",
	"FE_SIZE" : "Taille: ",
	"FE_DELETE_SELECTED" : "Supprimer la selection",
	"FE_INSERT_SELECTED" : "Inséré la selection",
	"FE_VIEWS" : "Vues: ",
	"FE_VIEW_MINIATURE" : "Vue miniature",
	"FE_VIEW_DETAILS" : "Vue détaillée",
	"FE_NOMBRE" : "Nom",
	"FE_TIPO" : "Type",
	"FE_TAMANO" : "Taille",
	"FE_DATE" : "Date",
	"FE_ACTIONS" : "Actions",
	"FE_VIEW" : "Vue",
	"FE_DOWNLOAD" : "Télécharcher",
	"FE_INFORMATION" : "Information",
	"FE_BACK" : "Retour",
	"BE_NEW_FOLDER_CREATED" : "Répertoire créé : ",
	"BE_NEW_FOLDER_EXISTED" : "Répertoire existant : ",
	"BE_GETFILEALL_NOT_LEIBLE" : "Fichier non lu",
	"BE_GETFILEALL_NOT_PERMITIDO" : "Fichier non autorisé",
	"BE_GETFILEALL_NOT_EXISTED" : "Fichier inexistant",
	"BE_UPLOADALL_UPLOADS" : "Envoyé : ",
	"BE_UPLOADALL_NOT_UPLOADS" : "Non autorisé: ",
	"BE_UPLOAD_MAX_UPLOAD" : "Nombre maximum de fichiers autorisé : ",
	"BE_DELETE_DELETED" : "Fichier supprimé",
	"BE_DELETE_NOT_EXIED" : "Fichier inexistant",
	"BE_RENAME_MODIFIED" : "Fichier modifié",
	"BE_RENAME_EXISTED" : "Fichier existant",
	"BE_RENAME_NOT_EXISTS" : "Fichier inexistant",
	"BE_RUN_NOT_VALID" : "Non valide : ",
	"BE_RENAME_EXT_NOT_EQUALS" : "L'extension est différente",
	"BE_RENAME_FILENAME_NOT_VALID" : "Nom de fichier non valide",
	"FE_MOVE" : "Déplacer",
	"BE_MOVE_MOVED" : "Fichier déplacé",
	"BE_MOVE_EXISTED" : "Le fichier existe déjà",
	"BE_MOVE_NOT_EXISTS" : "Fichier inexistant",
	"BE_MOVE_FILENAME_NOT_VALID" : "Nom de fichier non valide",
	"FE_FOLDER" : "Repertoire",
	"BE_MOVE_PATH_NOT_VALID" : "Chemin non valide",
	"BE_MOVE_FOLDER_EXISTED" : "Le répertoire existe déjà"
};