if(typeof LANGS == "undefined") var LANGS = {'RU':{}};
LANGS.RU = {
	"FE_UPLOAD" : "Загрузить файлы",
	"FE_CREATE_DIRECTORY" : "Создать папку",
	"FE_CANCEL" : "Отмена",
	"FE_DELETE" : "Удалить",
	"FE_CLEAR" : "Очистить",
	"FE_SEARCH_NAME_FILES" : "Поиск",
	"FE_ADD_FILES" : "Добавить",
	"FE_START_UPLOAD" : "Загрузить",
	"FE_CANCEL_UPLOAD" : "Отменить",
	"FE_NEW_FOLDER" : "Новая папка",
	"FE_NAME" : "Имя",
	"FE_CLOSE" : "Закрыть",
	"FE_SAVE" : "Сохранить",
	"FE_RENAME" : "Переименовать",
	"FE_ENTER_NAME" : "Введитите имя",
	"FE_MAX_FILES_UPLOAD" : "Максимальное число файлов: ",
	"FE_FILENAME" : "Имя файла: ",
	"FE_LAST_MODIFIED" : "Обновлено: ",
	"FE_SIZE" : "Размер: ",
	"FE_DELETE_SELECTED" : "Удалить выделеные",
	"FE_INSERT_SELECTED" : "Вставить выделеные",
	"FE_VIEWS" : "Вид: ",
	"FE_VIEW_MINIATURE" : "Плитка",
	"FE_VIEW_DETAILS" : "Таблица",
	"FE_NOMBRE" : "Имя",
	"FE_TIPO" : "Тип",
	"FE_TAMANO" : "Размер",
	"FE_DATE" : "Дата",
	"FE_ACTIONS" : "Действия",
	"FE_VIEW" : "Просмотр",
	"FE_DOWNLOAD" : "Загрузить",
	"FE_INFORMATION" : "Информация",
	"FE_BACK" : "Назад",
	"BE_NEW_FOLDER_CREATED" : "Папка создана: ",
	"BE_NEW_FOLDER_EXISTED" : "Папка существует: ",
	"BE_GETFILEALL_NOT_LEIBLE" : "Файл недоступен",
	"BE_GETFILEALL_NOT_PERMITIDO" : "Файл не допустим",
	"BE_GETFILEALL_NOT_EXISTED" : "Файл не существует",
	"BE_UPLOADALL_UPLOADS" : "Загружено: ",
	"BE_UPLOADALL_NOT_UPLOADS" : "Не загружено: ",
	"BE_UPLOAD_MAX_UPLOAD" : "Максимальное число файлов: ",
	"BE_DELETE_DELETED" : "Файл удален",
	"BE_DELETE_NOT_EXIED" : "Файл не существует",
	"BE_RENAME_MODIFIED" : "Файл обновлен",
	"BE_RENAME_EXISTED" : "Файл существует",
	"BE_RENAME_NOT_EXISTS" : "Файл не существует",
	"BE_RUN_NOT_VALID" : "Не допустимо: ",
	"BE_RENAME_EXT_NOT_EQUALS" : "Неверный формат файла",
	"BE_RENAME_FILENAME_NOT_VALID" : "Неправильное имя файла",
	"FE_MOVE" : "Переместить",
	"BE_MOVE_MOVED" : "Файл перемещен",
	"BE_MOVE_EXISTED" : "Файл уже существует",
	"BE_MOVE_NOT_EXISTS" : "Файл не существует",
	"BE_MOVE_FILENAME_NOT_VALID" : "Неправильное имя файла",
	"FE_FOLDER" : "Папка",
	"BE_MOVE_PATH_NOT_VALID" : "Неверный путь",
	"BE_MOVE_FOLDER_EXISTED" : "Папка уже существует"
};