if(typeof LANGS == "undefined") var LANGS = {'US':{}};
LANGS.US = {
	"FE_UPLOAD" : "Upload Files",
	"FE_CREATE_DIRECTORY" : "Create folder",
	"FE_CANCEL" : "Cancel",
	"FE_DELETE" : "Delete",
	"FE_CLEAR" : "Clear",
	"FE_SEARCH_NAME_FILES" : "Search files",
	"FE_ADD_FILES" : "Add Files",
	"FE_START_UPLOAD" : "Start upload",
	"FE_CANCEL_UPLOAD" : "Cancel upload",
	"FE_NEW_FOLDER" : "New folder",
	"FE_NAME" : "Name",
	"FE_CLOSE" : "Close",
	"FE_SAVE" : "Save",
	"FE_RENAME" : "Rename",
	"FE_ENTER_NAME" : "Enter name",
	"FE_MAX_FILES_UPLOAD" : "Max number of files: ",
	"FE_FILENAME" : "Name file: ",
	"FE_LAST_MODIFIED" : "Last modified: ",
	"FE_SIZE" : "Size: ",
	"FE_DELETE_SELECTED" : "Delete selected",
	"FE_INSERT_SELECTED" : "Insert selected",
	"FE_VIEWS" : "Views: ",
	"FE_VIEW_MINIATURE" : "View miniature",
	"FE_VIEW_DETAILS" : "View details",
	"FE_NOMBRE" : "Name",
	"FE_TIPO" : "Type",
	"FE_TAMANO" : "Size",
	"FE_DATE" : "Date",
	"FE_ACTIONS" : "Actions",
	"FE_VIEW" : "View",
	"FE_DOWNLOAD" : "Download",
	"FE_INFORMATION" : "Information",
	"FE_BACK" : "Back",
	"BE_NEW_FOLDER_CREATED" : "Folder created: ",
	"BE_NEW_FOLDER_EXISTED" : "Folder existed: ",
	"BE_GETFILEALL_NOT_LEIBLE" : "File not readed",
	"BE_GETFILEALL_NOT_PERMITIDO" : "File not allowed",
	"BE_GETFILEALL_NOT_EXISTED" : "File not existed",
	"BE_UPLOADALL_UPLOADS" : "Upload: ",
	"BE_UPLOADALL_NOT_UPLOADS" : "Not allowed: ",
	"BE_UPLOAD_MAX_UPLOAD" : "Maximum files allowed: ",
	"BE_DELETE_DELETED" : "File deleted",
	"BE_DELETE_NOT_EXIED" : "File no existed",
	"BE_RENAME_MODIFIED" : "File modificaded",
	"BE_RENAME_EXISTED" : "File existed",
	"BE_RENAME_NOT_EXISTS" : "File not existed",
	"BE_RUN_NOT_VALID" : "Not valid: ",
	"BE_RENAME_EXT_NOT_EQUALS" : "The extension not equal",
	"BE_RENAME_FILENAME_NOT_VALID" : "Name file not valid",
	"FE_MOVE" : "Move",
	"BE_MOVE_MOVED" : "File moved",
	"BE_MOVE_EXISTED" : "File already exists",
	"BE_MOVE_NOT_EXISTS" : "File does not exist",
	"BE_MOVE_FILENAME_NOT_VALID" : "Name file not valid",
	"FE_FOLDER" : "Folder",
	"BE_MOVE_PATH_NOT_VALID" : "Path Invalid",
	"BE_MOVE_FOLDER_EXISTED" : "Folder already exists"
};