if(typeof LANGS == "undefined") var LANGS = {'US':{}};
LANGS.US = {
	"FE_UPLOAD" : "Upload Files",
	"FE_CREATE_DIRECTORY" : "Create folder",
	"FE_CANCEL" : "Cancel",
	"FE_DELETE" : "Delete",
	"FE_CLEAR" : "Clear",
	"FE_SEARCH_NAME_FILES" : "Search files",
	"FE_ADD_FILES" : "Add Files",
	"FE_START_UPLOAD" : "Start upload",
	"FE_CANCEL_UPLOAD" : "Cancel upload",
	"FE_NEW_FOLDER" : "New folder",
	"FE_NAME" : "Name",
	"FE_CLOSE" : "Close",
	"FE_SAVE" : "Save",
	"FE_RENAME" : "Rename",
	"FE_ENTER_NAME" : "Enter name",
	"FE_MAX_FILES_UPLOAD" : "Max number of files: ",
	"FE_FILENAME" : "Name file: ",
	"FE_LAST_MODIFIED" : "Last modified: ",
	"FE_SIZE" : "Size: ",
	"BE_NEW_FOLDER_CREATED" : "Folder created: ",
	"BE_NEW_FOLDER_EXISTED" : "Folder existed: ",
	"BE_GETFILEALL_NOT_LEIBLE" : "File not readed",
	"BE_GETFILEALL_NOT_PERMITIDO" : "File not permitido",
	"BE_GETFILEALL_NOT_EXISTED" : "File not existed",
	"BE_UPLOADALL_UPLOADS" : "Upload: ",
	"BE_UPLOADALL_NOT_UPLOADS" : "Not permitido: ",
	"BE_UPLOAD_MAX_UPLOAD" : "Máximo permitido: ",
	"BE_NEW_FOLDER_EXISTED" : "Existed: ",
	"BE_NEW_FOLDER_CREATED" : "Created: ",
	"BE_DELETE_DELETED" : "File deleted",
	"BE_DELETE_NOT_EXIED" : "File no existed",
	"BE_RENAME_MODIFIED" : "File modificaded",
	"BE_RENAME_EXISTED" : "File existed",
	"BE_RENAME_NOT_EXISTS" : "File not existed",
	"BE_RUN_NOT_VALID" : "Not valid: ",
	"BE_RENAME_EXT_NOT_EQUALS" : "The extension not equal",
	"BE_RENAME_FILENAME_NOT_VALID" : "Name file not valid"
};