if (typeof LANGS == "undefined")
	var LANGS = {
		'ZH' : {}
	};
LANGS.ZH = {
	"FE_UPLOAD" : "上传文件",
	"FE_CREATE_DIRECTORY" : "创建文件夹",
	"FE_CANCEL" : "取消",
	"FE_DELETE" : "删除",
	"FE_CLEAR" : "清除",
	"FE_SEARCH_NAME_FILES" : "搜索文件",
	"FE_ADD_FILES" : "新增文件",
	"FE_START_UPLOAD" : "开始上传",
	"FE_CANCEL_UPLOAD" : "取消上传",
	"FE_NEW_FOLDER" : "新增文件夹",
	"FE_NAME" : "名称",
	"FE_CLOSE" : "关闭",
	"FE_SAVE" : "保存",
	"FE_RENAME" : "重命名",
	"FE_ENTER_NAME" : "输入名称",
	"FE_MAX_FILES_UPLOAD" : "最大上传文件个数: ",
	"FE_FILENAME" : "文件名: ",
	"FE_LAST_MODIFIED" : "最近修改时间: ",
	"FE_SIZE" : "大小: ",
	"FE_DELETE_SELECTED" : "删除选中的",
	"FE_INSERT_SELECTED" : "插入选中的",
	"FE_VIEWS" : "视图: ",
	"FE_VIEW_MINIATURE" : "缩略图展示",
	"FE_VIEW_DETAILS" : "列表展示",
	"FE_NOMBRE" : "名称",
	"FE_TIPO" : "类型",
	"FE_TAMANO" : "大小",
	"FE_DATE" : "日期",
	"FE_ACTIONS" : "操作",
	"FE_VIEW" : "查看",
	"FE_DOWNLOAD" : "下载",
	"FE_INFORMATION" : "信息",
	"FE_BACK" : "返回",
	"BE_NEW_FOLDER_CREATED" : "文件夹已被创建: ",
	"BE_NEW_FOLDER_EXISTED" : "文件夹已存在: ",
	"BE_GETFILEALL_NOT_LEIBLE" : "文件不能被读取",
	"BE_GETFILEALL_NOT_PERMITIDO" : "不允许此类型文件",
	"BE_GETFILEALL_NOT_EXISTED" : "文件已不存在",
	"BE_UPLOADALL_UPLOADS" : "上传: ",
	"BE_UPLOADALL_NOT_UPLOADS" : "不允许: ",
	"BE_UPLOAD_MAX_UPLOAD" : "最大允许: ",
	"BE_DELETE_DELETED" : "文件已被删除",
	"BE_DELETE_NOT_EXIED" : "文件已不存在",
	"BE_RENAME_MODIFIED" : "文件已被修改",
	"BE_RENAME_EXISTED" : "文件已存在",
	"BE_RENAME_NOT_EXISTS" : "文件已不存在",
	"BE_RUN_NOT_VALID" : "无效: ",
	"BE_RENAME_EXT_NOT_EQUALS" : "扩展名不一致",
	"BE_RENAME_FILENAME_NOT_VALID" : "文件名无效",
	"FE_MOVE" : "移动",
	"BE_MOVE_MOVED" : "文件已被移动",
	"BE_MOVE_EXISTED" : "文件已经存在",
	"BE_MOVE_NOT_EXISTS" : "文件不存在",
	"BE_MOVE_FILENAME_NOT_VALID" : "文件名无效",
	"FE_FOLDER" : "文件夹",
	"BE_MOVE_PATH_NOT_VALID" : "路径无效",
	"BE_MOVE_FOLDER_EXISTED" : "文件已经存在",
	"FE_FILE_TYPE" : "目录"
};
